### ISSUE TITLE
Critical section

### ISSUE THREAD

**Issue by Sanzo00** [sengorajkumar/gpu_graph_algorithms#2]
Great project! But there are some bugs:

There has some there may be multiple threads that meet the if condition at the same time. They will all use `atomicExch()` to exchange the value to `d_out_Di[]`. At this time, some threads may override the minimum value.
https://github.com/sengorajkumar/gpu_graph_algorithms/blob/983ba47db7411bf012af2848bd9ffa6336e9a94f/gpu/kernels.cu#L203-L206

Therefore, the two versions of the code (cuda-stride & cuda-v3) get different results.

![Snipaste_2021-01-24_18-32-35](https://user-images.githubusercontent.com/36565277/105628749-b7a48b80-5e79-11eb-85c7-a7d259c21823.jpg)

Although the correct distance can be obtained by using `atomicMin()`, there is still no guarantee that the `d_out_P[]` is correct.

I have another way to implement it, update `d_out_P[]` after Bellman-Ford is completed, here is my code:

https://github.com/Sanzona/Bellman-Ford/blob/01f2e2eafcb54a09dc8a863dc63d2e133afc0d79/code/kernels.cu#L88-L105

![Snipaste_2021-01-24_19-26-51](https://user-images.githubusercontent.com/36565277/105628809-27b31180-5e7a-11eb-8a57-7363dbc10a47.jpg)

**Comment by sengorajkumar** [comment]
@Sanzona Thanks for the feedback. Glad that you found the project interesting. Good catch on the issues and Great solution as well.  Just want to make the pull request includes updatePredWithGridStride that you mentioned here. It would be great to merge it so that the fixes are available for anyone that checks out in future. Can you please confirm?

**Comment by Sanzo00** [comment]
Thanks for your reply, I have added the updatePredWithGridStride() to the pull request, please check.

**Comment by sengorajkumar** [comment]
@Sanzona Awesome! Have merged the pull request. thank you!
